# Generated by Django 4.2.4 on 2023-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_password',
            field=models.IntegerField(null=True),
        ),
    ]
