# Generated by Django 4.2.4 on 2023-08-13 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0002_user_pin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(help_text='session_code hasable', max_length=200)),
                ('user', models.OneToOneField(help_text='this is user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
